name: Lint TypeScript

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/lint-typescript.yml'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - '**/*.lockb'
      - '**/package.json'
  pull_request:
    paths:
      - '.github/workflows/lint-typescript.yml'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.jsx'
      - '**/*.json'
      - '**/*.lockb'
      - '**/package.json'

jobs:
  tsc:
    name: Compile TypeScript (tsc)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: reviewdog/action-setup@v1

      - name: Install npm dependencies (bun)
        run: bun install

      - name: Run TypeScript (tsc)
        run: |
          bun typescript | reviewdog -name="tsc" -efm="%f(%l,%c): error TS%n: %m" -reporter="github-pr-review" -filter-mode="nofilter" -fail-on-error -tee
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  lint:
    name: Lint TypeScript (eslint, prettier)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v1
      - uses: reviewdog/action-setup@v1

      - name: Install npm dependencies (bun)
        run: bun install

      - name: Run ESLint
        run: bun lint -f @jamesacarr/github-actions

      - name: Run ESLint with auto-fix
        run: bun lint-fix

      - name: Verify no files have changed after auto-fix
        run: git diff --exit-code HEAD
